### ISSUE TITLE
PR upstream status ?

### ISSUE THREAD

**Issue by intika** [Druco/plasma-nm-wireguard#14]
Following your upstream pr https://phabricator.kde.org/D15093

i would like to know its status, its not very clear on phabricator... is it merged ?

**Comment by Druco** [comment]
No, the code is not yet merged. Phabricator is a tool for managing code reviews and the plasma-nm-wireguard is still under review. It has been a fairly long review process, mostly because this is the first KDE project I have worked on and there were many things I did that worked but were not in the KDE style or method of doing things. Hopefully the review is nearing the end and it will be merged when that happens.

**Comment by intika** [comment]
Yes i know that PR ing on phabricator is a long process... i my self did one or two PR there and ended published my modification on opendesktop because of the lack of time to edit the code to meet upstream conditions.... 

i closed other issues i opened as the code is being worked on, on kde... 

At least this get the job done and its what's more important, so thanks a lot !!! great work :)

**Comment by intika** [comment]
Just reviewed the code under phabricator and updated my local version... that's cool, great work :+1: still need some modifications but it's near merging so thanks a lot !

**Comment by intika** [comment]
Also something that i noticed building my custom rpm package... you did not include translations i guess you will be asked for on phabricator before merging...

**Comment by Druco** [comment]
Actually, I initially had copied the translations from one of the other VPN implementations but was told to delete them as the KDE build process evidently adds them automatically when released so they will hopefully be there.

**Comment by intika** [comment]
cool :) ...
i just finished building my rpms... will reboot and see how it goes :) 
thanks again !!!

**Comment by intika** [comment]
Done... 
Wow great release ! all of my previous issues seem to be solved on that version. 
so thanks again

**Comment by intika** [comment]
i just updated my fork as a mirrored version of phabricator... and published my rpms... it could help some users in the same case as me... any way thanks again !!!
