### ISSUE TITLE
Save button remain grayed when adding new VPN

### ISSUE THREAD

**Issue by intika** [Druco/plasma-nm-wireguard#18]
After filling all the necessary infos when adding a VPN the save button still remain grayed

I had to play a little but with selecting un-selecting other option to get it to be clickable... 

Under IPv4 tab selecting anything then back to "automatic" made the button clickable in my case... 

I know that i posted a lot here... i don't really have the time right now to debug correct the code but i will PR if i have some time to work on it... 

Thanks a lot for your work you plugin rocks !!!!!! 
its amazing, thanks again 

Note : i did not find your repo easily when i was googling after wireguard for plasma... plus you used a different username on kde site... so... any way was just to let you know... this could may be explain why this is not a lot of dev following this over here

**Comment by Druco** [comment]
As mentioned in comments on other issues, this is old code and any updates are currently being made during the review process on phabricator. Quite a bit of work was done in the area of input validation so I don't think this will be a problem in the future.

As soon as the review is finished the code will be in the official plasma-nm repository on the KDE site and I will delete this repository entirely to avoid confusion.

As I mentioned, this was originally a hack job for my own use so I am glad that somebody else is finding it useful.

**Comment by intika** [comment]
okay i guess the
